title = "im_kavin"
author = "Kavinraja G"
description = """
Cloud ğŸŒ©ï¸ Containers ğŸ³ what not? ğŸš€
Senior Engineer - Cloud & DevOps
"""
profilePicture = "images/profile.jpg"

favicon = "favicons/"
reversepagetitle = true
enableEmoji = true
fullPostContent = true
contentratio = 0.7

## Theme settings
displayMode = "dark"
disableThemeSwitcher = true

## Social links
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/kavinganesan/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Kavinraja-G/"

## Sidebar settings
hidesidebar = true